version: '3'
services:
  db:
    image: mysql:8.0
    tty: true
    platform: linux/x86_64
    container_name: task_db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - todo-db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

volumes:
  todo-db-volume: